version: '2'

services:
  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:6.6.2
    restart: always
    env_file:
      - .env
    environment:
      MONGO_URL: mongodb://rocketchat-mongodb:27030/rocketchat
      MONGO_OPLOG_URL: mongodb://rocketchat-mongodb:27030/local"
      ROOT_URL: http://localhost:3131
      PORT: 3131
      DEPLOY_METHOD: docker
      DEPLOY_PLATFORM: linux
      REG_TOKEN: ${REG_TOKEN:-}
    depends_on:
      - rocketchat-mongodb
    expose:
      - 3131
    ports:
      - 3131:3131
    networks:
      - scantist-network
      - default

  rocketchat-mongodb:
    image: docker.io/bitnami/mongodb:4.4
    env_file:
      - .env
    restart: always
    volumes:
      - mongodb_data:/bitnami/mongodb
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: rs0
      MONGODB_PORT_NUMBER: 27030
      MONGODB_INITIAL_PRIMARY_HOST: rocketchat-mongodb
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: 27030
      MONGODB_ADVERTISED_HOSTNAME: rocketchat-mongodb
      MONGODB_ENABLE_JOURNAL: "true"
      ALLOW_EMPTY_PASSWORD: "yes"

volumes:
  mongodb_data: { driver: local }

networks:
  scantist-network:
    external: true
  default: